import sys

__author__ = 'South Mountain'


def p2(n):
    """
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.
    """
    fibonacci(n, 1, 2, 2)

def fibonacci(n, first, second, result):
    """fibonacci"""
    if second >= n:
        print("Answer of the Problem 2nd is %d" % result)
        return

    nx = first + second
    if nx % 2 == 0:
        result += nx
    fibonacci(n, second, nx, result)

if __name__ == '__main__':
    p2(89)
    p2(4*1000000)
    sys.exit(0)
